
CREATE TABLE [dbo].[FX_Common_LOV_Parent](
	[TypeId] [bigint] IDENTITY(1,1) NOT NULL,
	[TypeName] [varchar](100) NOT NULL,
	[IsDisable] [int] NOT NULL,
 CONSTRAINT [PK_Common_LOV_Parent] PRIMARY KEY CLUSTERED 
(
	[TypeId] ASC,
	[TypeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FX_Common_LOV_Parent] ADD  CONSTRAINT [DF_Common_LOV_Parent_isDisabled]  DEFAULT (0) FOR [IsDisable]
GO


