//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Pages.eForms.iRental.Modules
{


    public partial class CarRateDetails
    {

        /// <summary>
        /// conCarRateDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conCarRateDetails;

        /// <summary>
        /// frmCarRateDetails_ShUc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmCarRateDetails_ShUc;

        /// <summary>
        /// grdCarRateDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdCarRateDetails;

        /// <summary>
        /// frmCarRateDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmCarRateDetails;
    }
}
