//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Pages.eForms.iRental.Modules
{


    public partial class SparePartInventoryInvoice
    {

        /// <summary>
        /// conInvoice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conInvoice;

        /// <summary>
        /// frmSparePartInventoryInvoice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmSparePartInventoryInvoice;

        /// <summary>
        /// frmInvoice_Cust_ShUc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmInvoice_Cust_ShUc;

        /// <summary>
        /// grdInvoice_Cust control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdInvoice_Cust;

        /// <summary>
        /// frmInvoiceDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmInvoiceDetails;

        /// <summary>
        /// frmInvoice_Cust_Quotation_ShU control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmInvoice_Cust_Quotation_ShU;

        /// <summary>
        /// grdInvoice_Cust_Quotation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdInvoice_Cust_Quotation;

        /// <summary>
        /// frmInvoiceDetails_Quotation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmInvoiceDetails_Quotation;

        /// <summary>
        /// frmCarServiceDetailsForInvoice_Cars control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmCarServiceDetailsForInvoice_Cars;

        /// <summary>
        /// grdCarServiceDetailsForInvoice_Cars control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdCarServiceDetailsForInvoice_Cars;

        /// <summary>
        /// frmInvoiceItemCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmInvoiceItemCode;

        /// <summary>
        /// grdInvoiceItemCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdInvoiceItemCode;
    }
}
