//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Pages.eForms.Accounts.Modules
{


    public partial class LedgerManagement
    {

        /// <summary>
        /// conLedgerManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conLedgerManagement;

        /// <summary>
        /// frmLedgerManagementCustomerDetails_Beneficary_ShUc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmLedgerManagementCustomerDetails_Beneficary_ShUc;

        /// <summary>
        /// grdLedgerManagement_Beneficary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdLedgerManagement_Beneficary;

        /// <summary>
        /// frmLedgerManagementCustomerDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmLedgerManagementCustomerDetails;

        /// <summary>
        /// frmLedgerManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmLedgerManagement;
    }
}
