//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.AsyncWidgets
{


    public partial class eFormsAdmin
    {

        /// <summary>
        /// mnuTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable mnuTable;

        /// <summary>
        /// TabPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.TabPanel TabPanel1;

        /// <summary>
        /// conGlobalInbox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conGlobalInbox;

        /// <summary>
        /// grdGlobalInbox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdGlobalInbox;

        /// <summary>
        /// conOrgSetup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conOrgSetup;

        /// <summary>
        /// frmSearchOrg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmSearchOrg;

        /// <summary>
        /// OrgSetup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid OrgSetup;

        /// <summary>
        /// frmNewOrg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmNewOrg;

        /// <summary>
        /// frmUpdateOrg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmUpdateOrg;

        /// <summary>
        /// conOrgUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conOrgUnit;

        /// <summary>
        /// frmSearchOrgUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmSearchOrgUnit;

        /// <summary>
        /// grdOrgUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdOrgUnit;

        /// <summary>
        /// frmUpdateOrgUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmUpdateOrgUnit;

        /// <summary>
        /// frmNewOrgUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmNewOrgUnit;

        /// <summary>
        /// conManageUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conManageUsers;

        /// <summary>
        /// frmSearchUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmSearchUsers;

        /// <summary>
        /// GrdUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid GrdUser;

        /// <summary>
        /// frmAddUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmAddUser;

        /// <summary>
        /// conRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conRoles;

        /// <summary>
        /// frmSearchRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmSearchRoles;

        /// <summary>
        /// grdRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdRoles;

        /// <summary>
        /// conProcessManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conProcessManagement;

        /// <summary>
        /// frmSearchProcessManagment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmSearchProcessManagment;

        /// <summary>
        /// grdProcRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdProcRoles;

        /// <summary>
        /// Container1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container Container1;

        /// <summary>
        /// conWelcome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conWelcome;

        /// <summary>
        /// conProcessGeneralSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conProcessGeneralSettings;

        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form Form1;

        /// <summary>
        /// frmProcessGS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmProcessGS;

        /// <summary>
        /// innerTabPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.TabPanel innerTabPanel1;

        /// <summary>
        /// conQuickView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conQuickView;

        /// <summary>
        /// frmAddQuickView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmAddQuickView;

        /// <summary>
        /// grdQuickView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdQuickView;

        /// <summary>
        /// conDocumentLibrary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conDocumentLibrary;

        /// <summary>
        /// frmDocumentLib control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmDocumentLib;

        /// <summary>
        /// grdSPDocTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdSPDocTypes;

        /// <summary>
        /// frmNewDocLibType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmNewDocLibType;

        /// <summary>
        /// conRolesTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conRolesTab;

        /// <summary>
        /// frmAddEditAssignRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmAddEditAssignRoles;

        /// <summary>
        /// grdProcGenralRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdProcGenralRoles;

        /// <summary>
        /// conSubmissionService control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conSubmissionService;

        /// <summary>
        /// frmSumission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmSumission;

        /// <summary>
        /// conRecrodMovement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conRecrodMovement;

        /// <summary>
        /// conEmailConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conEmailConfiguration;

        /// <summary>
        /// grdEmailConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdEmailConfiguration;

        /// <summary>
        /// conRuleEngine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conRuleEngine;

        /// <summary>
        /// conMassApprove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conMassApprove;

        /// <summary>
        /// conEmployeeLogin1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conEmployeeLogin1;

        /// <summary>
        /// frmEmployeeInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmEmployeeInfo;

        /// <summary>
        /// grdStuAtt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdStuAtt;

        /// <summary>
        /// conEmployeeLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conEmployeeLogin;

        /// <summary>
        /// grdStudentInvoice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdStudentInvoice;

        /// <summary>
        /// frmNewStudentInvoice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmNewStudentInvoice;

        /// <summary>
        /// frmUpdateStudentInvoice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Form frmUpdateStudentInvoice;

        /// <summary>
        /// conCommonLOV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conCommonLOV;

        /// <summary>
        /// grdParentLOV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid grdParentLOV;

        /// <summary>
        /// conLOVChild control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.Container conLOVChild;

        /// <summary>
        /// DataGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebProject.AsyncWidgets.Widgets.DataGrid DataGrid1;
    }
}
